// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CashflowChartController from "./cashflow_chart_controller"
application.register("cashflow-chart", CashflowChartController)

import CashflowFormController from "./cashflow_form_controller"
application.register("cashflow-form", CashflowFormController)

import CropPanelController from "./crop_panel_controller"
application.register("crop-panel", CropPanelController)

import FertilizationCalendarController from "./fertilization_calendar_controller"
application.register("fertilization-calendar", FertilizationCalendarController)
